In [ ]:
import pandas as pd

taxonomy = pd.read_csv("taxonomy.csv")

birds_taxonomy = taxonomy[taxonomy["class_name"] == "Aves"].copy()

birds_taxonomy[["primary_label", "common_name", "scientific_name", "class_name"]].head()

   primary_label           common_name           scientific_name class_name
72       ashgre1  Ashy-headed Greenlet     Hylophilus pectoralis       Aves
73       astcra1    Ash-throated Crake  Mustelirallus albicollis       Aves
74       bafcur1   Bare-faced Curassow           Crax fasciolata       Aves
75       baffal1  Barred Forest-Falcon      Micrastur ruficollis       Aves
76        banana            Bananaquit          Coereba flaveola       Aves

In [2]:
print("Nombre total de classes :", len(taxonomy))
print("Nombre de classes d'oiseaux :", len(birds_taxonomy))

Nombre total de classes : 234
Nombre de classes d'oiseaux : 162

In [6]:
from pathlib import Path

train_audio_dir = Path("train_audio")

rows = []

for _, row in birds_taxonomy.iterrows():
    label = row["primary_label"]
    folder = train_audio_dir / label

    if folder.exists():
        n_audio = len(list(folder.glob("*.ogg")))
        
        rows.append({
            "primary_label": label,
            "common_name": row["common_name"],
            "scientific_name": row["scientific_name"],
            "n_audio": n_audio
        })

birds_classes = pd.DataFrame(rows)

birds_classes = birds_classes.sort_values("n_audio", ascending=False)

birds_classes.head(20)

,primary_label,common_name,scientific_name,n_audio
98,rubthr1,Rufous-bellied Thrush,Turdus rufiventris,499
4,banana,Bananaquit,Coereba flaveola,498
39,fepowl,Ferruginous Pygmy Owl,Glaucidium brasilianum,497
126,soulap1,Southern Lapwing,Vanellus chilensis,497
59,houspa,House Sparrow,Passer domesticus,496
77,osprey,Osprey,Pandion haliaetus,495
30,coffal1,Collared Forest-Falcon,Micrastur semitorquatus,495
123,socfly1,Social Flycatcher,Myiozetetes similis,494
31,compau,Pauraque,Nyctidromus albicollis,493
161,yeofly1,Yellow-olive Flatbill,Tolmomyias sulphurescens,493
15,bncfly,Brown-crested Flycatcher,Myiarchus tyrannulus,492
16,bobfly1,Boat-billed Flycatcher,Megarynchus pitangua,492
142,trsowl,Tropical Screech Owl,Megascops choliba,491
8,bbwduc,Black-bellied Whistling Duck,Dendrocygna autumnalis,491
153,whtdov,White-tipped Dove,Leptotila verreauxi,491
122,sobtyr1,Southern Beardless Tyrannulet,Camptostoma obsoletum,490
97,roahaw,Roadside Hawk,Rupornis magnirostris,489
133,strcuc1,Striped Cuckoo,Tapera naevia,485
141,trokin,Tropical Kingbird,Tyrannus melancholicus,483
51,grekis,Great Kiskadee,Pitangus sulphuratus,482

In [7]:
selected_classes = birds_classes.head(6)

selected_classes

    primary_label            common_name         scientific_name  n_audio
98        rubthr1  Rufous-bellied Thrush      Turdus rufiventris      499
4          banana             Bananaquit        Coereba flaveola      498
39         fepowl  Ferruginous Pygmy Owl  Glaucidium brasilianum      497
126       soulap1       Southern Lapwing      Vanellus chilensis      497
59         houspa          House Sparrow       Passer domesticus      496
77         osprey                 Osprey       Pandion haliaetus      495

In [8]:
selected_classes["primary_label"].to_csv(
    "classes.txt",
    index=False,
    header=False
)

In [9]:
selected_classes.to_csv("selected_classes.csv", index=False)

In [10]:
df = pd.read_csv("splits/audio_split_65_15_20.csv")

train_df = df[df["split"] == "train"]
val_df = df[df["split"] == "val"]
test_df = df[df["split"] == "test"]